const mongoose = require("mongoose");

const AUTO_ISBN_PREFIX = {
  Course: "COURSE",
  default: "BOOK",
};

const STANDARD_ISBN_REGEX = /^(?:\d{9}[\dXx]|\d{13})$/;

const getIsbnPrefix = (format) =>
  format === "Course" ? AUTO_ISBN_PREFIX.Course : AUTO_ISBN_PREFIX.default;

const generateProductIsbn = (format, documentId) => {
  const id = documentId || new mongoose.Types.ObjectId();
  return `${getIsbnPrefix(format)}-${id}`;
};

const isAutoGeneratedIsbn = (isbn, format) => {
  if (!isbn) return false;
  const prefix = getIsbnPrefix(format);
  return isbn.startsWith(`${prefix}-`);
};

const isValidIsbn = (value, format) => {
  if (!value) return true;

  const isbn = String(value).trim();
  if (isAutoGeneratedIsbn(isbn, format)) return true;

  if (format === "Course" && isbn.startsWith("COURSE-")) return true;
  if (format !== "Course" && isbn.startsWith("BOOK-")) return true;

  return STANDARD_ISBN_REGEX.test(isbn.replace(/[-\s]/g, ""));
};

const normalizeProvidedIsbn = (value) => {
  if (!value) return null;
  const isbn = String(value).trim();
  if (!isbn) return null;
  if (isbn.startsWith("COURSE-") || isbn.startsWith("BOOK-")) return isbn;
  return isbn.replace(/[-\s]/g, "");
};

module.exports = {
  generateProductIsbn,
  isAutoGeneratedIsbn,
  isValidIsbn,
  normalizeProvidedIsbn,
};
